// lib/mockUsers.ts
import type { ApiUser } from "./api";

export const MOCK_USERS: ApiUser[] = [
  {
    id: "u1",
    login: "maria_dev",
    hashPassword: "hash",
    photoHash: "",
    name: "Мария",
    surName: "Иванова",
    fatherName: "Сергеевна",
    age: 24,
    gender: "female",
    describeUser: "Frontend-разработчица, люблю React и UX-анимации.",
    city: "Москва",
    contact: "@maria",
    skills: [
      { id: "s1", userId: "u1", skillName: "React", user: "u1" },
      { id: "s2", userId: "u1", skillName: "TypeScript", user: "u1" },
    ],
    interests: [
      { id: "i1", userId: "u1", interestName: "UI", user: "u1" },
      { id: "i2", userId: "u1", interestName: "Анимации", user: "u1" },
    ],
    hobbies: [{ id: "h1", userId: "u1", hobbyName: "Йога", user: "u1" }],
    requests: [],
  },
  {
    id: "u2",
    login: "pavel_back",
    hashPassword: "hash",
    photoHash: "",
    name: "Павел",
    surName: "Петров",
    fatherName: "Андреевич",
    age: 28,
    gender: "male",
    describeUser: "Backend-инженер, фанат чистой архитектуры и кофе.",
    city: "Санкт-Петербург",
    contact: "@pavel",
    skills: [
      { id: "s3", userId: "u2", skillName: "Go", user: "u2" },
      { id: "s4", userId: "u2", skillName: "PostgreSQL", user: "u2" },
    ],
    interests: [{ id: "i3", userId: "u2", interestName: "БД", user: "u2" }],
    hobbies: [{ id: "h2", userId: "u2", hobbyName: "Футбол", user: "u2" }],
    requests: [],
  },
  {
    id: "u3",
    login: "katya_ai",
    hashPassword: "hash",
    photoHash: "",
    name: "Екатерина",
    surName: "Соколова",
    fatherName: "Игоревна",
    age: 26,
    gender: "female",
    describeUser: "ML/LLM энтузиаст, делаю прототипы и демо.",
    city: "Казань",
    contact: "@katya",
    skills: [
      { id: "s5", userId: "u3", skillName: "Python", user: "u3" },
      { id: "s6", userId: "u3", skillName: "PyTorch", user: "u3" },
    ],
    interests: [{ id: "i4", userId: "u3", interestName: "LLM", user: "u3" }],
    hobbies: [{ id: "h3", userId: "u3", hobbyName: "Фотография", user: "u3" }],
    requests: [],
  },
];
